projects:
  todoreactaws:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: 3d4nrgl2bndspm4ba7uy4fsahe
      endpoints:
        prod: >-
          https://47k5ucoyczgqldsypropmhvwri.appsync-api.us-east-2.amazonaws.com/graphql
